Erik dev
dasava11/front_project_board_games pull request #112
Opened 2023-07-12 21:31 UTC by ErikMortensen

2023-07-12 23:03 UTC, dasava11 requested changes
Revisar conflictos de App.jsx

2023-07-12 23:03 UTC, dasava11 commented on ecommerce_front/src/App.jsx
Revisar App, presenta conflictos

2023-07-12 23:57 UTC, ErikMortensen commented
ahi quedo

2023-07-13 00:00 UTC, dasava11 approved these changes

2023-07-13 00:00 UTC, merged